import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--data_dir", default=None, type=str, required=True, help="The input raw_data dir. Should contain the .tsv files (or other raw_data files) for the task.", )
parser.add_argument("--model_type", default="bert", type=str, required=False, help="Model type selected in the list: ")
parser.add_argument("--model_name_or_path", default=None, type=str, required=True, help="Path to pre-trained model ")
parser.add_argument("--language", default="zh", type=str, required=False, help="Evaluation language. Also train language if `train_language` is set to None.", )
parser.add_argument("--train_language", default=None, type=str, help="Train language if is different of the evaluation language.")
parser.add_argument("--output_dir", default=None, type=str, required=True, help="The output directory where the model predictions and checkpoints will be written.", )
parser.add_argument("--input_test_name", default="test.tsv", type=str, help="The output directory where the model predictions and checkpoints will be written.", )
parser.add_argument("--test_ouptut_path", default=None, type=str, help="The output directory where the model predictions and checkpoints will be written.", )
# Other parameters
parser.add_argument("--config_name", default="", type=str, help="Pretrained config name or path if not the same as model_name")
parser.add_argument("--tokenizer_name", default="", type=str, help="Pretrained tokenizer name or path if not the same as model_name", )
parser.add_argument("--cache_dir", default="", type=str, help="Where do you want to store the pre-trained models downloaded from s3", )
parser.add_argument("--task_name", default="", type=str, help="Which task", )
parser.add_argument("--max_seq_length", default=128, type=int, help="The maximum total input sequence length. Sequences longer than this will be truncated,shorter will be padded.", )
parser.add_argument("--do_train", action="store_true", help="是否进行模型训练")  # store_true 传入这个参数则默认为True，没传入则默认为False
parser.add_argument("--do_eval", action="store_true", help="是否进行模型评估")
parser.add_argument("--do_predict", action="store_true", help="是否进行预测")
parser.add_argument("--min_span_length", default=3, type=int, help="指定匹配的kb实体的最小长度")
parser.add_argument("--is_debug", action="store_true", help="只用前若干条数据进行调试代码")
parser.add_argument("--pipeline_el_md_dir", type=str, help="实体链接的md得分输出路径")
parser.add_argument("--pipeline_el_ed_dir", type=str, help="实体链接的ed得分输出路径")
parser.add_argument("--compute_pipeline_el_metric", action="store_true", help="计算pipeline实体链接得分")
parser.add_argument("--kg_name", default="nlpcc",type=str, help="使用的知识图谱")
parser.add_argument("--evaluate_during_training", action="store_true", help="Rul evaluation during training at each logging step.")
parser.add_argument("--do_lower_case", action="store_true", help="Set this flag if you are using an uncased model.")
parser.add_argument("--per_gpu_train_batch_size", default=32, type=int, help="Batch size per GPU/CPU for training.")
parser.add_argument("--per_gpu_eval_batch_size", default=256, type=int, help="Batch size per GPU/CPU for evaluation.")
parser.add_argument("--gradient_accumulation_steps", type=int, default=1, help="Number of updates steps to accumulate before performing a backward/update pass.", )
parser.add_argument("--learning_rate", default=5e-5, type=float, help="The initial learning rate for Adam.")
parser.add_argument("--weight_decay", default=0.0, type=float, help="Weight decay if we apply some.")
parser.add_argument("--adam_epsilon", default=1e-8, type=float, help="Epsilon for Adam optimizer.")
parser.add_argument("--max_grad_norm", default=1.0, type=float, help="Max gradient norm.")
parser.add_argument("--num_train_epochs", default=3.0, type=float, help="Total number of training epochs to perform.")
parser.add_argument("--warmup_steps", default=0, type=int, help="Linear warmup over warmup_steps.")
parser.add_argument("--logging_steps", type=int, default=500, help="Log every X updates steps.")
parser.add_argument("--save_steps", type=int, default=99999, help="Save checkpoint every X updates steps.")  # 默认在训练过程不保存模型参数
parser.add_argument("--eval_all_checkpoints", action="store_true", help="Evaluate all checkpoints starting with the same prefix as model_name ending and ending with step number", )
parser.add_argument("--no_cuda", action="store_true", help="Avoid using CUDA when available")
parser.add_argument("--overwrite_output_dir", action="store_true", help="Overwrite the content of the output directory")
parser.add_argument("--overwrite_cache", action="store_true", help="Overwrite the cached training and evaluation sets")
parser.add_argument("--seed", type=int, default=123, help="random seed for initialization")
parser.add_argument("--server_ip", type=str, default="", help="For distant debugging.")
parser.add_argument("--server_port", type=str, default="", help="For distant debugging.")
# metrics 评估模型的指标 以 保存dev中表现最好的模型
# Option acc,acc@1,acc@2,acc@3,默认是acc
parser.add_argument("--metrics", type=str, default="acc", help="For save best train model.")
# 使用含有kg实体边界的数据集
parser.add_argument("--kg_enhance", action="store_true", help="For dataset use entity border(mention & candidate entity).")
parser.add_argument("--kg_enhance_2", action="store_true", help="For dataset use entity and kg border(mention & candidate entity & kg overlabwords).")
parser.add_argument("--kg_enhance_3", action="store_true", help="For dataset use entity border(mention & candidate entity) but mask kg subgraph tokens.")
parser.add_argument("--ccks_no_1", action="store_true", help="For dataset use entity border(mention & candidate entity) but mask kg subgraph tokens.")

args = parser.parse_args()
